services:
  backend:
    image: remommender-backend:latest
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "/your/folder/here:/data"
    environment:
      SECRET_KEY: "django-insecure-39yrg+3$9&*%o7nohp@ruihd)d_t%-jdmb_h)@8he*u=43z!hh"
      MEDIA_ROOT: "/data/srv"
      SQL_DIR: "/data/db.sqlite3"
      MODEL_PATH: "/data/Models"