version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH}db:/data/db

  apache:
    image: httpd:2.4
    container_name: apache_fileserver
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - ${DATA_PATH}Audio:/usr/local/apache2/htdocs/Audio
      - ${DATA_PATH}Album_Art:/usr/local/apache2/htdocs/Album_Art