# Generated by Django 3.1.12 on 2025-07-18 08:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artwork', models.FileField(upload_to='Album_Art/')),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valence', models.FloatField(blank=True, null=True)),
                ('arousal', models.FloatField(blank=True, null=True)),
                ('authenticity', models.FloatField(blank=True, null=True)),
                ('timeliness', models.FloatField(blank=True, null=True)),
                ('complexity', models.FloatField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('tonal', models.FloatField(blank=True, null=True)),
                ('voice', models.FloatField(blank=True, null=True)),
                ('bpm', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='Audio/')),
            ],
        ),
        migrations.CreateModel(
            name='SongGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top3_genres', models.JSONField(default=dict)),
                ('all_genres', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('duration_s', models.FloatField()),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.artworkfile')),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.songfile')),
                ('features', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='core.songfeatures')),
                ('genres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='core.songgenres')),
            ],
        ),
    ]
