# Generated by Django 5.2.1 on 2025-09-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_songfeatures_id_alter_songgenres_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artwork',
            new_name='artwork_file',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artwork',
            new_name='album',
        ),
    ]
