# Generated by Django 5.2.1 on 2025-09-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_artwork_album_artwork_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='Audio/'),
        ),
        migrations.DeleteModel(
            name='SongFile',
        ),
    ]
