# Generated by Django 4.2.25 on 2025-10-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_song_audio_file_delete_songfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='album_name',
        ),
    ]
